# Generated by Django 4.2.6 on 2023-11-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diaries'},
        ),
        migrations.AlterModelOptions(
            name='diarycomment',
            options={'verbose_name_plural': 'Diary Comments'},
        ),
        migrations.AlterModelOptions(
            name='diarycommit',
            options={'verbose_name_plural': 'Diary Commits'},
        ),
        migrations.AddField(
            model_name='diarycomment',
            name='diary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diaries.diary'),
            preserve_default=False,
        ),
    ]
