# Generated by Django 4.2.6 on 2023-11-09 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_alter_diary_options_alter_diarycomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarycomment',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diarycommit',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diarycommit',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='diaries.diary'),
        ),
    ]
