# Generated by Django 4.2.6 on 2023-11-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_xp'),
        ('diaries', '0003_diarycomment_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='accounts.account'),
        ),
    ]
