# Generated by Django 4.2.6 on 2023-12-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_xp'),
        ('diaries', '0004_alter_diary_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='comments_last_read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='diarycomment',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diaries.diary'),
        ),
    ]
