# Generated by Django 4.2.6 on 2023-11-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_xp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XP',
        ),
    ]
