# ===== XP
ADDITIONAL_GROWING_XP_PER_LEVEL = 50
XP_PER_DAIRY_COMMIT = 5
MESSAGE_LENGTH_WHICH_BRINGS_XP_IN_DIARY_COMMIT = 50
LEVEL_STEP_THAT_CHANGE_COLOR_DESIGN = 3

# ===== RULES
COMMIT_MIN_LENGTH = 10
