# ===== XP
ADDITIONAL_GROWING_XP_PER_LEVEL = 50
XP_PER_DAIRY_COMMIT = 5
MESSAGE_LENGTH_WHICH_BRINGS_XP_IN_DIARY_COMMIT = 50
LEVEL_STEP_THAT_CHANGE_COLOR_DESIGN = 3
STAR_FILLING_BONUS_VALUE = 5
ADDITIONAL_XP_FOR_STAR_FILLING = 28

# ===== RULES
COMMIT_MIN_LENGTH = 10
BANNED_WORDS_IN_MORE_DETAILED_MESSAGE = [
    "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun",
    "+0500", "Nov", "Dec", "Jan", "Feb", "Mar",
]
