# Generated by Django 4.2.6 on 2023-11-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clans', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('priority', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(related_name='issues_from_assignee', to='accounts.account')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clans.clan')),
                ('reviewers', models.ManyToManyField(related_name='issues_from_reviewer', to='accounts.account')),
            ],
        ),
    ]
