# Generated by Django 4.2.6 on 2023-11-03 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
