# Generated by Django 4.2.6 on 2023-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
